jasp-stats/jaspFactor

DESCRIPTION, R/confirmatoryfactoranalysis.R, inst/help/confirmatoryfactoranalysis.md, inst/help/confirmatoryfactoranalysis_nl.md, inst/qml/FactorsForm.qml
Fixes [#379](https://github.com/jasp-stats/jasp-issues/issues/379)
=> Allow ordinal variables in CFA

DESCRIPTION, R/confirmatoryfactoranalysis.R, inst/qml/ConfirmatoryFactorAnalysis.qml
fixes [#886](https://github.com/jasp-stats/jasp-issues/issues/886)
=> Add std par. in plot

R/confirmatoryfactoranalysis.R, R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R, inst/qml/ExploratoryFactorAnalysis.qml, inst/qml/PrincipalComponentAnalysis.qml, tests/testthat/test-exploratoryfactoranalysis.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/1215
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1213
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1214
=> Add radiobutton to sort factor loadings

R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R
Fixes #4 
If you use this filter:
then the error was before:
and after this PR:
=> Improve error check as suggested in #4

DESCRIPTION, R/confirmatoryfactoranalysis.R, tests/testthat/test-confirmatoryfactoranalysis.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1258
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1257
=> Fix bootstrapping and check whether covariance pairs are specified

.github/workflows/unittests.yml, R/principalcomponentanalysis.R, tests/testthat/test-principalcomponentanalysis.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1500
Does not fix https://github.com/jasp-stats/jasp-test-release/issues/1490.
Adds a bunch of unit tests for all available rotation methods.
=> Fix test issue about missing function

R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R, inst/qml/ExploratoryFactorAnalysis.qml, inst/qml/PrincipalComponentAnalysis.qml, tests/testthat/test-exploratoryfactoranalysis.R, tests/testthat/test-verified-exploratoryfactoranalysis.R, tests/testthat/test-verified-principalcomponentanalysis.R
Reverts jasp-stats/jaspFactor#49
My bad, I clicked merge too early
=> Revert "Fixing the Slider Label"

R/confirmatoryfactoranalysis.R
fixes https://github.com/jasp-stats/jasp-issues/issues/1548
Context: The bug was the same as in jaspSem that we fixed earlier (damn column decoding!): https://github.com/jasp-stats/jaspSem/pull/16
Unfortunately we cannot catch this bug in tests because it only fails in JASP (damn column encoding!)
=> fix path plot with ordinal variables

R/confirmatoryfactoranalysis.R, R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R
Hi, I fixed some missing `gettext()` calls. I haven't compiled, but I think the fixes are straight-forward.
=> Add some missing gettext() to enable translation.

R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/1734
=> Fix empty factor correlation table

R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R
- fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/1701
by using `cor` instead of `cov` for the data
=> Scree plot fix for incorrect displayed data eigen values

R/confirmatoryfactoranalysis.R, inst/Upgrades.qml, inst/qml/ConfirmatoryFactorAnalysis.qml
fixes https://github.com/jasp-stats/jasp-issues/issues/1730
=> Rotation and font size options added to improve readability

R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/1959
=> fix scree plot

R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R
- fixes https://github.com/jasp-stats/jasp-test-release/issues/1977 with a more informative message 
- fixes https://github.com/jasp-stats/jasp-test-release/issues/1978 with a more informative error message
- fixes https://github.com/jasp-stats/jasp-test-release/issues/1979
=> Fix test-release issues

R/confirmatoryfactoranalysis.R, inst/qml/ConfirmatoryFactorAnalysis.qml
fixes https://github.com/jasp-stats/jasp-test-release/issues/2019
=> parameter symbols consistent plot/table

.gitignore, R/exploratoryfactoranalysis.R, R/principalcomponentanalysis.R, inst/help/ExploratoryFactorAnalysis.md, inst/help/PrincipalComponentAnalysis.md, inst/qml/ExploratoryFactorAnalysis.qml, inst/qml/PrincipalComponentAnalysis.qml, tests/testthat/test-exploratoryfactoranalysis.R, tests/testthat/test-principalcomponentanalysis.R, tests/testthat/test-verified-exploratoryfactoranalysis.R
fixes https://github.com/jasp-stats/jaspFactor/issues/110
fixes https://github.com/jasp-stats/jasp-issues/issues/1639
adds parallel analysis table for PCA
=> Residual matrix (EFA/PCA) and more fit indices (EFA)

R/confirmatoryfactoranalysis.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/2289
=> Fix jasp release error

R/confirmatoryfactoranalysis.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/2294
=> Fix jasp release error(s)

R/confirmatoryfactoranalysis.R, inst/qml/ConfirmatoryFactorAnalysis.qml
fixes https://github.com/jasp-stats/jasp-issues/issues/2182
=> Fix grouping bug

R/confirmatoryfactoranalysis.R
fixes https://github.com/jasp-stats/jasp-issues/issues/2182
=> Fix group bug

R/confirmatoryfactoranalysis.R, inst/qml/ConfirmatoryFactorAnalysis.qml, tests/testthat/test-confirmatoryfactoranalysis.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2619
=> fix data reading

R/confirmatoryfactoranalysis.R, renv.lock, renv/activate.R
fixes https://github.com/jasp-stats/jasp-issues/issues/3550
for testing 
[err.jasp.zip](https://github.com/user-attachments/files/21547719/err.jasp.zip)
=> fix residual cor bug
